import Header from "@/components/auth/common/Header";
import ProgressBar from "@/components/common/ProgressBar";

export const metadata = {
  title: "Sow-pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProgressBar />
        <Header />
        {children}
      </body>
    </html>
  );
}
